name: Ejecutor de Rastreador de Ofertas

on:
  schedule:
    # Corre automáticamente en la hora de Perú a las:
    # 6:00 AM, 12:00 PM, 6:00 PM y 10:00 PM (Traducido a formato UTC)
    - cron: '0 11,17,23,3 * * *'
  workflow_dispatch: # Mantiene activo tu botón manual por si quieres forzar la revisión

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar mi código
      uses: actions/checkout@v4

    - name: Configurar Entorno Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar herramientas necesarias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Correr Rastreador y Enviar Mensaje
      run: python scraper.py

    # ESTO PERMITE AL ROBOT GUARDAR EL HISTORIAL DE PRECIOS EN TU REPOSITORIO
    - name: Guardar Historial de Precios Actualizado
      run: |
        git config --global user.name "Bot de Ofertas"
        git config --global user.email "bot@ofertas.com"
        git add historial_precios.json || true
        git commit -m "Actualizar historial de precios [skip ci]" || true
        git push || true
